version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "sample_app_docker_development"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./:/myapp
    ports:
      - '3000:3000'
    depends_on:
      - db
    links:
      - "sidekiq:sidekiq"
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - tmpdb:/var/lib/redis/data
  sidekiq:
    build: .
    command: 'bundle exec sidekiq'
    volumes:
      - ./:/myapp
    environment:
      RAILS_ENV: "development"
      REDIS_URL: "redis://redis:6379/12"
    depends_on:
      - db
      - redis
volumes:
  db:
  tmpdb: